export const FETCH_LIKE_POST_ERROR = 'FETCH_LIKE_POST_ERROR';
export const FETCH_LIKE_POST_SUCCESS = 'FETCH_LIKE_POST_SUCCESS';

export const FETCH_LIKE_POSTS_ERROR = 'FETCH_LIKE_POSTS_ERROR';
export const FETCH_LIKE_POSTS_SUCCESS = 'FETCH_LIKE_POSTS_SUCCESS';
